[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/run/supervisord.pid

[program:syslogd]
command=sh -c "mkdir -p /var/log/haproxy /var/run/haproxy && exec busybox syslogd -n -O /var/log/haproxy/haproxy.log"
priority=10
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:apache2]
command=/usr/sbin/httpd -D FOREGROUND
priority=20
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:haproxy]
command=/usr/local/sbin/haproxy -f /usr/local/etc/haproxy/haproxy.cfg -db
priority=30
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0