version: "3.7"

services:
  caddy:
    image: caddy:latest
    container_name: Caddy
    network_mode: host
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/caddy/html:/srv"
      - "/caddy/data:/data"
      - "/caddy/config:/config"
