---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /mnt/config:/config
      - /mnt/software/TVShows:/tv
      - /mnt/movies:/movies
    restart: unless-stopped
