version: '3'
services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: d!8U&J!8v8L1pFBK
    volumes:
      - mongoVol:/data/db
volumes:
  mongoVol:
