mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
        - '1433:1433'
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Thinbirds1!
    volumes:
        - 'mssqlVol:/var/opt/mssql'
    ports:
      - 1433:1433
