services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server'
    ports:
      - '1433:1433'
    environment:
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Thinbirds1!
    volumes:
      - 'mssqlVol:/var/opt/mssql'

volumes:
  mssqlVol:
