version: "3.6"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    network_mode: bridge
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  portainer_data:
